config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root :to => redirect("users/sign_in")
  root "tasks#index"
  resources :tasks do 
    resources :sub_tasks 
  end 
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title , presence: true , length: {minimum:3}
  validates :description, presence: true , length: {maximum: 50}
  has_and_belongs_to_many :users
  belongs_to :user
  has_many :sub_tasks , dependent: :destroy
  VALID_STATUSES = ['completed', 'in-progress', 'paused']
  validates :status, inclusion: { in: VALID_STATUSES }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    if user_signed_in? 
      if current_user.role == 'admin'
        @tasks = Task.all 
      else 
        user = User.find_by(id: current_user.id)
        @tasks = user.tasks
      end
    end
  end

  def new
    @task = Task.new 
    @users = User.all
  end

  def show
    @task = Task.find(params[:id])    
    @users = User.all
  end

  def create 
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    if @task.save 
      redirect_to tasks_path
    else 
      render :new, status: :unprocessable_entity
    end 
  end

  def edit
    @task = Task.find(params[:id])
  end    
 
  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path
    else  
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @task = Task.find(params[:id])
    @task.destroy  
    redirect_to root_path, status: :see_other
  end

  private 
  def task_params 
    params.require(:task).permit(:title, :description, :status)
  end

end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/tasks/_form.html.erb
<form class="p-4" >
  <%= form_with model: @task do |form| %> 
  <div class="form-group">
    <%= form.label :title, class: "form-label" %> <br>
    <%= form.text_field :title, class: "form-control" %> 
    <% @task.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description, class: "form-label" %> <br>
    <%= form.text_area :description, class: "form-control" %>
    <% @task.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>

<% end %>
</form>

app/views/tasks/edit.html.erb
<div class="container" >
  <h1>Edit task</h1>

<%= render 'form'%>
</div>

app/views/tasks/index.html.erb
<div class="container" >
  <h1>Your Tasks</h1>

<% if user_signed_in? %>
  <% if current_user.role == 'admin' %>
    <h4> <%= link_to 'New task', new_task_path %> </h4>
  <% end %>
  <ul>
    <% @tasks.each do |task| %> 
    <table class="table">
      
      <tbody>
        <tr>
          
          <td><%= link_to task.title, task_path(task) %></td>
          <% if current_user.role == 'admin' %>
            <td><%= link_to 'Edit', edit_task_path(task) %></td>
            <td><%= link_to 'Destroy', task, data: {
              turbo_method: :delete, 
              turbo_confirm: "Are you sure?"
              }  %></td>
          <% end %> 
          
        </tr>
       
      </tbody>
    </table>
    
    
    
    <% end %>
  </ul>
<% else %>
   <h4>Please Sign in for creating a new task and see tasks</h4>
<% end %>




</div>

app/views/tasks/new.html.erb
<div class="container" >
  <h1>Create Task</h1>

<%= form_with model: @task do |form| %> 
  <div class="form-group">
    <%= form.label :title, class: "form-label" %> <br>
    <%= form.text_field :title, class: "form-control" %> 
    <% @task.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description, class: "form-label" %> <br>
    <%= form.text_area :description, class: "form-control" %>
    <% @task.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <p>
    <%= form.label :status %><br>
    <%= form.select :status,  selected: ['in-progress' , 'completed', 'paused'] %>
  </p>

  <div>
    <%= form.submit %>
  </div>

  <% end %>

  </div>

app/views/tasks/show.html.erb
<div class="container" >
  <h1>  Title:  <%= @task.title %> </h1>
  <p>  description: <%= @task.description %> </p>


<h2>Sub Tasks</h2>
<% @task.sub_tasks.each do |sub_task| %>
  <p>
    title: <%= sub_task.title %>
  </p>

  <p>
    <strong>description:</strong>
    <%= sub_task.description %>
  </p>


  <p>
    <strong>status:</strong>
    <%= sub_task.status %>
  </p>
  <% if user_signed_in? %>
     
  <% end %>

  <p> <%= link_to 'Edit', edit_task_sub_task_path(sub_task) %> </p>
  
<% end %>

  <% if current_user.role == "admin" %>
    <%= form_with model: [ @task, @task.sub_tasks.build ] do |form| %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    </p>
    <p>
      <%= form.label :status %><br>
      <%= form.select :status,  selected: ['in-progress' , 'completed', 'paused'] %>
    </p>
    <p>
      <%= form.submit %>
    </p>
    <ul>
      <li> <%= link_to 'Edit', edit_task_path(@task) %> </li>
    </ul>
  <% end %>
<% end %>


</div>